// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TyeExplorer
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidTyeExplorerPackageString = "1e58a7e2-226e-4353-95ec-8d4e88408a19";
        public static Guid guidTyeExplorerPackage = new Guid(guidTyeExplorerPackageString);

        public const string guidTyeExplorerCommandsAndMenusString = "0ccfef2f-31d2-4ac0-9bff-69faba97a675";
        public static Guid guidTyeExplorerCommandsAndMenus = new Guid(guidTyeExplorerCommandsAndMenusString);

        public const string guidImagesString = "65097361-2cf4-4df2-a8cc-f359b02a51ba";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidTyeExplorerLogWindowString = "f59325cd-5dbb-4d28-82ac-f5fa48390bdb";
        public static Guid guidTyeExplorerLogWindow = new Guid(guidTyeExplorerLogWindowString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int TyeExplorer_Toolbar = 0x0010;
        public const int TyeExplorer_Toolbar_General = 0x0020;
        public const int TyeExplorer_Toolbar_Services = 0x0030;
        public const int TyeExplorer_Menu_Attach = 0x0040;
        public const int TyeExplorer_OpenWindow = 0x0100;
        public const int TyeExplorer_ReloadServices = 0x0110;
        public const int TyeExplorer_OpenDashboard = 0x0120;
        public const int TyeExplorer_AttachSelected = 0x0130;
        public const int TyeExplorer_AttachAll = 0x0140;
        public const int TyeExplorer_AttachStartupProjects = 0x0150;
        public const int TyeExplorer_OpenLoggingSelected = 0x0160;
        public const int bmpLogo = 0x0001;
        public const int bmpReload = 0x0002;
        public const int bmpHome = 0x0003;
        public const int bmpProcess = 0x0004;
        public const int bmpOutput = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}